### ISSUE TITLE
error created with " using {classSymbol.ContainingNamespace.ToDisplayString()}.Helpers; "

### ISSUE THREAD

**Issue by Dyyt587** [kitUIN/ShadowPluginLoader.WinUI#1]
![image](https://github.com/user-attachments/assets/c1e27c83-eff4-4066-9ebd-adeaae23180c)
这个代码导致产生了报错 using {classSymbol.ContainingNamespace.ToDisplayString()}.Helpers;  

这句话是不需要的，或者有其他的用意？

**Comment by kitUIN** [comment]
信息过少
能否直接提供代码仓库

**Comment by kitUIN** [comment]
理论上，helpers命名空间是由源生成器自动生成的，或许你可以先构建一次试试

**Comment by Dyyt587** [comment]
> 信息过少 能否直接提供代码仓库

这个是我的代码[ACOM](https://github.com/kitUIN/ShadowPluginLoader.WinUI/issues/1#issuecomment-2540336777),在[第19行](https://github.com/Dyyt587/ACOM/blob/acom_v2/plugin_test2/slide.cs)，我通过创建一个空的命名空间暂时解决了这个问题

**Comment by Dyyt587** [comment]
> 理论上，helpers命名空间是由源生成器自动生成的，或许你可以先构建一次试试

是的，我当时翻阅自动生成的那个软件包发现了这个东西，我还发现他是由于国际化生成的，先构建不起作用，实际上，它会产生图片上面这样的报错，并且无法转跳到那个文件，我打开对应文件发现是空的，猜测可能是自动创建错误后就不将错误的文件写入而直接删除导致

**Comment by kitUIN** [comment]
这个命名空间确实没啥用，没必要在源生成器里使用，我去掉就行了
